name: neobahaso
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  rxdart: ^0.27.4
  formz: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
    - family: NunitoBold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
    - family: NunitoLight
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
    - family: NunitoMedium
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
    - family: NunitoSemiBold
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: NunitoBlackItalic
      fonts:
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: LatoBold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: LatoItalic
      fonts:
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
    - family: LatoLight
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
